

# Basic
name:               "Lab25"
title:              "chcho"
description:        "Unam"

pemalink: pretty


# URL
url:                https://bouzaslab25.github.io/

# Markdown
markdown:           kramdown
